Repository DinoTools/dionaea, pull requests merged in 2018-03, with the labels that each got.

#151 Added bistream for HTTPS
  src/connection_tls.c
Labels: type:enhancement

#158 doc - Add tips and tricks
  doc/source/index.rst
  doc/source/tips_and_tricks.rst
Labels: documentation

#114 Update tips_and_tricks.rst
  doc/source/old/tips_and_tricks.rst
Labels: documentation

#159 Install ubuntu1604
  doc/source/installation.rst
Labels: documentation

#165 introduce the PYTHON_SITELIB variable to the makefile
  modules/python/dionaea/Makefile.am
Labels: type:enhancement

#163 get rid of one of the compile time warnings about not using the chdir
  src/dionaea.c
Labels: type:enhancement

#160 fix the compile time problem with GLIB libraries
  modules/curl/Makefile.am
  modules/emu/Makefile.am
  modules/nc/Makefile.am
  modules/nfq/Makefile.am
  modules/nl/Makefile.am
  modules/pcap/Makefile.am
  modules/xmatch/Makefile.am
Labels: type:bugfix
