Repository DinoTools/dionaea, pull requests merged in 2018-06, with the labels that each got.

#202 Migrate from autoconf to cmake
  .gitignore
  CHANGELOG.rst
  CMakeLists.txt
  cmake/InstallConfig.cmake
  cmake/InstallPythonConfig.cmake
  cmake/Packaging.cmake
  conf/dionaea.cfg.cmake
  conf/ihandlers/fail2ban.yaml.in
  conf/ihandlers/log_db_sql.yaml.in
  conf/ihandlers/log_incident.yaml.in
  conf/ihandlers/log_json.yaml.in
  conf/ihandlers/log_sqlite.yaml.in
  conf/ihandlers/virustotal.yaml.in
  conf/services/ftp.yaml.in
  conf/services/http.yaml.in
  conf/services/sip.yaml.in
  conf/services/tftp.yaml.in
  conf/services/upnp.yaml.in
  config.h.cmake
  doc/source/index.rst
  doc/source/migration.rst
  modules/python/CMakeLists.txt
  modules/python/setup.py.in2
  src/CMakeLists.txt
  src/dionaea.c
Labels: type:bugfix, type:enhancement

#204 Correct typo in documentation
  doc/source/configuration.rst
Labels: typo

#208 Ipv4 mapped ipv6
  CHANGELOG.rst
  CMakeLists.txt
  cmake/CheckIPv4MappedIPv6.cmake
  conf/dionaea.cfg.cmake
  config.h.cmake
  doc/source/migration.rst
  src/util.c
Labels: type:enhancement

#209 Use cmake defined dirs
  config.h.cmake
  modules/python/module.c
  src/modules.c
Labels: type:enhancement

#212 build - remove autotools config
  Makefile.am
  conf/dionaea.cfg.in
  configure.ac
  include/Makefile.am
  m4/az_bind_ipv4_mapped_localhost.m4
  m4/az_python.m4
  modules/Makefile.am
  modules/curl/Makefile.am
  modules/emu/Makefile.am
  modules/nc/Makefile.am
  modules/nfq/Makefile.am
  modules/nl/Makefile.am
  modules/pcap/Makefile.am
  modules/python/Makefile.am
  modules/python/dionaea/Makefile.am
  modules/python/setup.py.in
  modules/python/util/Makefile.am
  modules/xmatch/Makefile.am
  src/Makefile.am
Labels: type:enhancement

#213 Release 0.8.0
  CHANGELOG.rst
  CMakeLists.txt
Labels: type:enhancement

#149 Added more information in the filename of the bistream
  src/processor.c
Labels: type:enhancement

#217 Fix reconnect with IP only
  src/connection.c
Labels: type:bugfix

#218 Use classes to provide additional information on connection errors
  modules/python/binding.pyx
  modules/python/dionaea/exception.py
  modules/python/dionaea/hpfeeds.py
Labels: type:enhancement
