Repository DinoTools/dionaea, pull requests merged in 2019-10, with the labels that each got.

#267 Drone CI
  .drone.yml
  ci/debian-8/dionaea/Dockerfile
  ci/debian-8/docker-compose.yml
  ci/debian-9/dionaea/Dockerfile
  ci/debian-9/docker-compose.yml
  ci/run.sh
  ci/ubuntu-14.04/dionaea/Dockerfile
  ci/ubuntu-14.04/docker-compose.yml
  ci/ubuntu-16.04/dionaea/Dockerfile
  ci/ubuntu-16.04/docker-compose.yml
  ci/ubuntu-18.04/dionaea/Dockerfile
  ci/ubuntu-18.04/docker-compose.yml
  conf/dionaea.cfg.cmake
  doc/source/configuration.rst
  doc/source/contributing.rst
  doc/source/development/index.rst
  doc/source/ihandler/emuprofile.rst
  doc/source/ihandler/fail2ban.rst
  doc/source/ihandler/ftp.rst
  doc/source/ihandler/hpfeeds.rst
  doc/source/ihandler/p0f.rst
  doc/source/ihandler/store.rst
  doc/source/ihandler/tftp_download.rst
  doc/source/installation.rst
  doc/source/migration.rst
  doc/source/service/blackhole.rst
  doc/source/service/epmap.rst
  doc/source/service/mirror.rst
  doc/source/service/mqtt.rst
  doc/source/service/pptp.rst
  doc/source/support.rst
  doc/source/tips_and_tricks.rst
Labels: type:enhancement

#266 Fix minor typos
  doc/source/introduction.rst
Labels: typo

#257 Updating default sip db path to reflect 0.8.0 changes
  modules/python/dionaea/sip/extras.py
Labels: type:bugfix

#268 Replace PyUnicode_GetSize in python module
  modules/python/module.c
Labels: type:bugfix, type:enhancement
