Repository DinoTools/dionaea, pull requests merged in 2020-11, with the labels that each got.

#301 Adds printer support - fixes #245
  conf/services/printer.yaml.in
  doc/source/service/index.rst
  doc/source/service/printer.rst
  modules/python/CMakeLists.txt
  modules/python/dionaea/printer.py
  tests/Makefile
  tests/printer/Makefile
  tests/printer/requirements.txt
  tests/printer/tests/__init__.py
  tests/printer/tests/test_pcl.py
  tests/printer/tests/test_pjl_commands.py
Labels: Type: Enhancement

#242 Add smb port option
  doc/source/service/smb.rst
  modules/python/dionaea/smb/__init__.py
  modules/python/dionaea/smb/extras.py
Labels: Type: Enhancement

#302 Enable mypy check
  .pre-commit-config.yaml
  modules/python/dionaea/smb/include/asn1/ber.py
Labels: Type: Enhancement

#303 Improve http service
  .flake8
  conf/services/http.yaml.in
  doc/source/service/http.rst
  modules/python/dionaea/http.py
  share/python/http/template/example/form.html.j2
  share/python/http/template/example/form.html.j2.license
Labels: Type: Enhancement

#307 Update installation instructions
  doc/source/installation.rst
Labels: Type: Documentation

#309 Improve handling of custom certificate files
  conf/dionaea.cfg.cmake
  include/connection.h
  src/connection.c
  src/connection_tls.c
Labels: Type: Enhancement

#312 Remove pyev
  README.md
  modules/python/binding.pyx
  modules/python/dionaea/__init__.py
  modules/python/dionaea/hpfeeds.py
  modules/python/dionaea/s3.py
  modules/python/dionaea/sip/__init__.py
  modules/python/dionaea/submit_http.py
  modules/python/dionaea/virustotal.py
  modules/python/module.c
  modules/python/pyev/Async.c
  modules/python/pyev/Async.c.license
  modules/python/pyev/Check.c
  modules/python/pyev/Check.c.license
  modules/python/pyev/Child.c
  modules/python/pyev/Child.c.license
  modules/python/pyev/Embed.c
  modules/python/pyev/Embed.c.license
  modules/python/pyev/Fork.c
  modules/python/pyev/Fork.c.license
  modules/python/pyev/Idle.c
  modules/python/pyev/Idle.c.license
  modules/python/pyev/Io.c
  modules/python/pyev/Io.c.license
  modules/python/pyev/Loop.c
  modules/python/pyev/Loop.c.license
  modules/python/pyev/Periodic.c
  modules/python/pyev/Periodic.c.license
  modules/python/pyev/PeriodicBase.c
  modules/python/pyev/PeriodicBase.c.license
  modules/python/pyev/Prepare.c
  modules/python/pyev/Prepare.c.license
  modules/python/pyev/Scheduler.c
  modules/python/pyev/Scheduler.c.license
  modules/python/pyev/Signal.c
  modules/python/pyev/Signal.c.license
  modules/python/pyev/Timer.c
  modules/python/pyev/Timer.c.license
  modules/python/pyev/Watcher.c
  modules/python/pyev/Watcher.c.license
  modules/python/pyev/pyev.c
  modules/python/pyev/pyev.c.license
  modules/python/setup.py.in2
Labels: Status: Complete, Type: Enhancement

#313 prepare 0.11.0
  CHANGELOG.rst
  CMakeLists.txt
  doc/source/migration.rst
Labels: Type: Release
