Repository DinoTools/dionaea, pull requests merged in 2020-09, with the labels that each got.

#287 Stop hpfeeds publishing before authenticating
  modules/python/dionaea/hpfeeds.py
Labels: Type: Enhancement

#269 Update mysql.py
  modules/python/dionaea/mysql/mysql.py
Labels: type:bugfix

#289 Prepare release 0.9.0
  CHANGELOG.rst
  CMakeLists.txt
Labels: Type: Release
